# Generated by Django 5.2.4 on 2025-07-23 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriPublikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(help_text='URL-friendly version of the category name', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori Publikasi',
                'verbose_name_plural': 'Kategori Publikasi',
            },
        ),
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Publikasi')),
                ('penulis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Penulis')),
                ('deskripsi_singkat', models.TextField(blank=True, null=True, verbose_name='Deskripsi Singkat')),
                ('keterangan_lengkap', models.TextField(blank=True, null=True, verbose_name='Keterangan Lengkap')),
                ('penerbit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Penerbit')),
                ('tanggal_publikasi', models.DateField(blank=True, null=True, verbose_name='Tanggal Publikasi')),
                ('bahasa', models.CharField(default='Bahasa Indonesia', max_length=50, verbose_name='Bahasa')),
                ('halaman', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jumlah Halaman')),
                ('link_eksternal', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Eksternal')),
                ('file_publikasi', models.FileField(blank=True, null=True, upload_to='publikasi_files/', verbose_name='File Publikasi')),
                ('gambar_sampul', models.ImageField(blank=True, null=True, upload_to='publikasi_covers/', verbose_name='Gambar Sampul')),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_profile.kategoripublikasi', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Publikasi',
                'verbose_name_plural': 'Publikasi',
                'ordering': ['-tanggal_publikasi', 'judul'],
            },
        ),
    ]
