# Generated by Django 5.2.4 on 2025-07-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Layanan')),
                ('slug', models.SlugField(blank=True, help_text='Slug akan dibuat otomatis dari judul', max_length=200, unique=True)),
                ('deskripsi_singkat', models.TextField(blank=True, help_text='Deskripsi singkat yang tampil di daftar layanan', verbose_name='Deskripsi Singkat')),
                ('deskripsi_lengkap', models.TextField(blank=True, help_text='Deskripsi lengkap yang tampil di halaman detail', verbose_name='Deskripsi Lengkap')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='layanan_images/', verbose_name='Gambar Layanan')),
                ('ikon_svg', models.CharField(blank=True, help_text='Tempelkan kode SVG untuk ikon (misal: dari Font Awesome SVG, Heroicons)', max_length=500, verbose_name='Kode Ikon SVG (opsional)')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Angka yang lebih kecil akan tampil lebih dulu', verbose_name='Urutan Tampilan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktifkan Layanan')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diperbarui')),
            ],
            options={
                'verbose_name': 'Layanan',
                'verbose_name_plural': 'Layanan',
                'ordering': ['urutan', 'judul'],
            },
        ),
    ]
